### ISSUE TITLE
Create a .gitignore file

### ISSUE THREAD

**Issue by jlewi** [gmartinez948/OrganProject#6]
See https://git-scm.com/docs/gitignore

A .gitignore file prevents certain files from being checked into the repo. This repo should have a .gitignore file which prevents things like
https://github.com/gmartinez948/OrganProject/tree/main/templates/__pycache__

From being checked in.  `.pyc` files should also be ignored.

As well as .DS_STORE
https://github.com/gmartinez948/OrganProject/blob/main/templates/.DS_Store

**Comment by gmartinez948** [comment]
****
