### ISSUE TITLE
Repo cleanup: Remove unused files

### ISSUE THREAD

**Issue by jlewi** [gmartinez948/OrganProject#8]
Can the following files be deleted?

https://github.com/gmartinez948/OrganProject/blob/main/organ_transplant_by_ethnicity.html
https://github.com/gmartinez948/OrganProject/blob/main/Staticpage.html
https://github.com/gmartinez948/OrganProject/blob/main/DonorEth_by_status%20(2).ipynb
https://github.com/gmartinez948/OrganProject/blob/main/.DS_Store

**Comment by gmartinez948** [comment]
Yes, doing that now
